# Generated by Django 3.2.9 on 2022-01-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_productcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
